name: Deployment pipeline

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: build
        run: npm run build
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Check the deployed service URL
        if: ${{ github.event_name == 'push' }}
        uses: jtalk/url-health-check-action@v3
        with:
        # Check the following URLs one by one sequentially
          url: https://hanasiu-pokemon.onrender.com|http://hanasiu-pokemon.onrender.com
        # Fail this action after this many failed attempts
          max-attempts: 3 # Optional, defaults to 1
        # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
  tag_release:
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip')  }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  # discord_message:
  #   if: ${{ github.event_name == 'push' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy Success
  #       if: ${{ success() }}
  #       uses: rjstone/discord-webhook-notify@v1
  #       with:
  #         severity: info
  #         details: Deploy Succeeded!
  #         webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  #     - name: Deploy Failure
  #       if: ${{ failure() }}
  #       uses: rjstone/discord-webhook-notify@v1
  #       with:
  #         severity: error
  #         details: Deploy Failed!
  #         webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}