name: render action

on: 
  push:
    branches:
      - master
jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.7.0
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          retries: 20
          wait: 16000
          sleep: 30000